#	from: @(#)Makefile	5.10 (Berkeley) 5/11/90
#	$Id: Makefile,v 1.3 1993/08/01 05:44:33 mycroft Exp $

PROG=	anpa
# -g turns on debuging info for gcc
CFLAGS+=-g
SRCS=	action.c getheader.c main.c parsectl.c printbody.c printheader.c \
	readf.c readrec.c selector.c setserial.c
#DPADD=	${LIBCURSES} ${LIBTERM}
#LDADD=	-lcurses -ltermlib
MAN1= anpa.1
MAN5= anpa.ctl.5

.include <bsd.prog.mk>
